### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [Urunov/TelegramBot-Vokzal-Ticket-RailwayStation#1]
Hi,<br><br>url : https://github.com/Urunov/TelegramBot-Vokzal-Ticket-RailwayStation/blob/c1ecab1ed9ea99ae95e2d3769173d2ce2af8bee1/RailwayStation-Vokzal-Ticket/src/main/resources/application.properties <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by Urunov** [comment]
Hello, 
shaybenb ,,, thank you, Updated.

Appericated

**Comment by Urunov** [comment]
Commit and update secure information.
thanks
